//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public int ID { get; set; }
        public string Language1 { get; set; }
        public string Founder { get; set; }
        public string Year { get; set; }
        public Nullable<bool> IsPopular { get; set; }
    }
}
